{ config, lib, ... }:

let
  cfg = config.gruvbox.doom;
  p = config.gruvbox.palette;
  inherit (config.gruvbox) flavor contrast;
in
{
  options.gruvbox.doom.enable =
    lib.mkEnableOption "gruvbox for doom emacs: writes ~/.config/doom/gruvbox.el, add (load! \"gruvbox\") to config.el and keep (package! gruvbox-theme) in packages.el" // { default = config.gruvbox.enable; };

  config = lib.mkIf cfg.enable {
    xdg.configFile."doom/gruvbox.el".text = ''
      ;;; gruvbox.el -*- lexical-binding: t; -*-
      ;;; generated by gruvbox.nix, do not edit

      (setq doom-theme 'gruvbox-${flavor}-${contrast})

      (custom-set-faces!
        '(mode-line :background "${p.bg1}")
        '(mode-line-inactive :background "${p.bg}"))

      (add-hook! 'dired-mode-hook
        (defun +gruvbox-dired-bg-h ()
          (face-remap-add-relative 'default :background "${p.bg0_h}")))
    '';
  };
}
