{ config, lib, options, ... }:

let
  gl = import ../lib.nix { inherit config lib options; };
  cfg = config.gruvbox.doom;
  p = gl.paletteOf cfg;
in
{
  options.gruvbox.doom = gl.mkModule "doom";

  config = lib.mkIf cfg.enable {
    xdg.configFile."doom/gruvbox.el".text = ''
      ;;; gruvbox.el -*- lexical-binding: t; -*-
      ;;; generated by gruvbox.nix, do not edit

      (setq doom-theme 'gruvbox-${cfg.flavor}-${cfg.contrast})

      (custom-set-faces!
        '(mode-line :background "${p.bg1}")
        '(mode-line-inactive :background "${p.bg}"))

      (add-hook! 'dired-mode-hook
        (defun +gruvbox-dired-bg-h ()
          (face-remap-add-relative 'default :background "${p.bg0_h}")))
    '';
  };
}
